{ config, lib, pkgs, ... }:
{
  home.packages = with pkgs; [
    # ── Terminals ────────────────────────────────────────────────
    alacritty
    kitty
    ghostty

    # ── Editors / IDE ────────────────────────────────────────────
    vscode

    # ── Wayland / Mango deps (юзер-пакеты) ───────────────────────
    waybar
    wl-clipboard
    wl-clip-persist
    cliphist
    wf-recorder
    satty
    slurp
    grim
    awww
    walker
    wlogout
    swaybg
    swayosd
    wlr-randr
    wlopm
    swaylock
    swayidle

    # ── Notification daemon ──────────────────────────────────────
    # Using dunst. omnix-theme-set / wallpaper-hypr.sh write a fresh
    # ~/.config/dunst/dunstrc (generated by pywal into ~/.cache/wal/
    # dunstrc) on each theme switch and `dunstctl reload`.
    # The systemd user unit shipped with the package is disabled below
    # in mpd.nix-sibling — it starts before mango sets WAYLAND_DISPLAY
    # and crashes trying to open X11. dunst is launched from
    # config/mango/conf/autostart.conf instead.
    dunst

    # ── Apps ──────────────────────────────────────────────────────
    brave
    chromium
    # Native discord package downloads "full.distro" from
    # stable.dl2.discordapp.net at build time, which is unreachable
    # from a lot of Russian networks (RKN blocking). Use vesktop
    # instead — it talks to Discord via the web client and ships as
    # a self-contained electron app.
    vesktop
    telegram-desktop
    keepassxc
    gajim
    senpai
    vlc
    mpv
    strawberry
    audacity
    obs-studio
    foliate
    papers
    transmission_4-gtk
    filezilla
    remmina
    flacon
    puddletag
    gnome-calculator
    libqalculate
    gimp
    nautilus
    gvfs
    imv
    ripdrag
    blueman
    mpc
    mpd
    mpdris2-rs
    rmpc
    cava
    fastfetch
    yazi
    btop
    dust
    gearlever
    gimagereader

    # ── Theming / tools ──────────────────────────────────────────
    pywal16
    waypaper
    whitesur-icon-theme
    whitesur-gtk-theme

    # ── nwg-* (раньше из кастомного void-repo) ───────────────────
    nwg-dock-hyprland
    nwg-drawer
    nwg-look

    # ── Launchers / Notifications ────────────────────────────────
    rofi
    libnotify

    # ── X11 fallback tools ───────────────────────────────────────
    xclip
    xsel
    xdotool
    maim
    slop

    # ── Audio utility deps (для bin/omnix-cmd-*) ─────────────────
    ffmpeg

    # ── Inotify / Python ─────────────────────────────────────────
    inotify-tools
    python3
    python3Packages.watchdog

    # ── OmnIX custom packages (из ./pkgs) ────────────────────────
    omnix-scripts
    photogimp-config
    wal-telegram
  ];

  services.cliphist.enable = true;
}
