{ config, lib, pkgs, osConfig, inputs, ... }:
{
  home.packages = with pkgs; [
    # ── Terminals ────────────────────────────────────────────────
    alacritty
    kitty
    ghostty

    # ── Editors / IDE ────────────────────────────────────────────
    vscode

    # ── Wayland / Mango deps (юзер-пакеты) ───────────────────────
    waybar
    wl-clipboard
    wl-clip-persist
    cliphist
    wf-recorder
    satty
    slurp
    grim
    awww
    walker
    wlogout
    swaybg
    swayosd
    wlr-randr
    wlopm
    swaylock
    swayidle

    # ── Notification daemon ──────────────────────────────────────
    # Using dunst. omnix-theme-set / wallpaper-hypr.sh write a fresh
    # ~/.config/dunst/dunstrc (generated by pywal into ~/.cache/wal/
    # dunstrc) on each theme switch and `dunstctl reload`.
    # The systemd user unit shipped with the package is disabled below
    # in mpd.nix-sibling — it starts before mango sets WAYLAND_DISPLAY
    # and crashes trying to open X11. dunst is launched from
    # config/mango/conf/autostart.conf instead.
    dunst

    # ── Apps (core — всегда ставятся) ────────────────────────────
    keepassxc
    gnome-calculator
    libqalculate
    gimp
    nautilus
    gvfs
    imv
    ripdrag
    blueman
    mpc
    mpd
    mpdris2-rs
    rmpc
    cava
    fastfetch
    yazi
    btop
    dust
    amnezia-vpn

    # ── Theming / tools ──────────────────────────────────────────
    pywal16
    waypaper
    #whitesur-icon-theme
    whitesur-gtk-theme
    (pkgs.whitesur-icon-theme.override {
        themeVariants = [ "default" "grey" "purple" "red" "orange" ];
    })

    # ── nwg-* (раньше из кастомного void-repo) ───────────────────
    #nwg-dock-hyprland
    nwg-drawer
    nwg-look

    # ── Launchers / Notifications ────────────────────────────────
    rofi
    libnotify

    # ── Audio utility deps (для bin/omnix-cmd-*) ─────────────────
    ffmpeg

    # ── Inotify / Python ─────────────────────────────────────────
    inotify-tools
    python3
    python3Packages.watchdog

    # ── OmnIX custom packages (из ./pkgs) ────────────────────────
    omnix-scripts
    photogimp-config
    wal-telegram
  ] ++ [
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
  ];
  # Опциональные наборы приложений (comms / media / office / gaming / …)
  # переехали в modules/system/apps.nix и включаются по категориям из
  # hosts/<host>/variables.nix.

  services.cliphist.enable = true;
}
